# Generated by Django 3.2.7 on 2021-09-29 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('r', 'Requested'), ('p', 'Purchased'), ('s', 'In Stock'), ('u', 'Unavailable'), ('d', 'Declined'), ('a', 'Archive')], default='r', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
