# Generated by Django 3.2.5 on 2021-08-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
