# This is a basic workflow to help you get started with Actions

name: Example CD Django to DigitalOcean

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push Main Branch into Production
        uses: codingforentrepreneurs/action-branch-to-branch@main
        with:
          dest_branch: production-3
          source_branch: main
          commit_message: "Release production version"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Run a DOCTL Command
        run: |
          doctl apps update ${{ secrets.DO_APP_ID }} --spec .do/app.yaml